import React from 'react'
import CIcon from '@coreui/icons-react'
import {
  cilArrowThickToRight,
  cilBank,
  cilDescription,
  cilDollar,
  cilHistory,
  cilHome,
  cilLink,
  cilMoney,
  cilPencil,
  cilPeople,
  cilPuzzle,
  cilReportSlash,
  cilStar,
  cilUser,
  cilUserPlus,
  cilWallet,
} from '@coreui/icons'
import { CNavGroup, CNavItem, CNavTitle } from '@coreui/react'

const _nav = [
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/admin-dashboard',
    icon: <CIcon icon={cilHome} customClassName="nav-icon" />,
    isAdmin: true,
  },
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/retailer-dashboard',
    icon: <CIcon icon={cilHome} customClassName="nav-icon" />,
    isRetailer: true,
  },
 {
    component: CNavItem,
    name: 'Dashboard',
    to: '/master-distributor-dashboard',
    icon: <CIcon icon={cilHome} customClassName="nav-icon" />,
    isMasterDistributor: true,
  },
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/master-admin-dashboard',
    icon: <CIcon icon={cilHome} customClassName="nav-icon" />,
    isMasterAdmin: true,
  },
 {
    component: CNavItem,
    name: 'Dashboard',
    to: '/distributor-dashboard',
    icon: <CIcon icon={cilHome} customClassName="nav-icon" />,
    isDistributor: true,
  },
 
  {
    component: CNavItem,
    name: 'Purchase Coupon',
    to: '/purchase-coupon',
    icon: <CIcon icon={cilArrowThickToRight} customClassName="nav-icon" />,
    isRetailer: true,
  },
  {
    component: CNavItem,
    name: 'Customize Website',
    to: '/customize-website',
    icon: <CIcon icon={cilPencil} customClassName="nav-icon" />,
    isAdmin: true,
  },
  {
    component: CNavItem,
    name: 'Approve User',
    to: '/approve-user',
    icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
    isMasterAdmin: true,
  },
  {
    component: CNavTitle,
    name: 'Partner Management',
    isAdmin: true,
    isMasterDistributor: true,
  },
  {
    component: CNavItem,
    name: 'Create Partner',
    to: '/create-partner',
    icon: <CIcon icon={cilUserPlus} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
  },
  {
    component: CNavItem,
    name: 'Partners',
    to: '/all-partners',
    icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
  },
  {
    component: CNavItem,
    name: 'Set Price',
    to: '/set-price',
    icon: <CIcon icon={cilDollar} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
  },
  {
    component: CNavGroup,
    name: 'Important Links',
    icon: <CIcon icon={cilLink} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Track UTI PAN Card',
        to: 'https://www.trackpan.utiitsl.com/PANONLINE/#forwards',
      },
      {
        component: CNavItem,
        name: 'Track NSDL PAN Card',
        to: 'https://tin.tin.nsdl.com/pantan/StatusTrack.html',
      },
      {
        component: CNavItem,
        name: 'UTI E-PAN Card',
        to: 'https://www.myutiitsl.com/PAN_ONLINE/ePANCard',
      },
      {
        component: CNavItem,
        name: 'NSDL E-PAN Card',
        to: 'https://www.onlineservices.nsdl.com/paam/MPanLogin.html',
      },
      {
        component: CNavItem,
        name: 'Reprint UTI PAN Card',
        to: 'https://www.myutiitsl.com/PAN_ONLINE/reprint',
      },
      {
        component: CNavItem,
        name: 'Reprint NSDL PAN Card',
        to: 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html',
      },
      {
        component: CNavItem,
        name: 'UTI PAN Link Status',
        to: 'https://www.myutiitsl.com/PAN_ONLINE/panTracker.do',
      },
    ],
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
    isRetailer: true,
  },
  {
    component: CNavTitle,
    name: 'Account / Other Settings',
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
    isRetailer: true,
  },
  {
    component: CNavItem,
    name: 'Wallet Withdrawal',
    to: '/wallet-withdrawal',
    icon: <CIcon icon={cilWallet} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
  },
  {
    component: CNavItem,
    name: 'Payments History',
    to: '/payments-history',
    icon: <CIcon icon={cilHistory} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
  },
  {
    component: CNavItem,
    name: 'Bank Account Setup',
    to: '/bank-account-setup',
    icon: <CIcon icon={cilBank} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
    isRetailer: true,
  },
  {
    component: CNavItem,
    name: 'Add to Wallet',
    to: '/add-to-wallet',
    icon: <CIcon icon={cilDollar} customClassName="nav-icon" />,
    isRetailer: true,
  },
  {
    component: CNavItem,
    name: 'Complaint',
    to: '/complaint',
    icon: <CIcon icon={cilReportSlash} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
    isRetailer: true,
  },
  {
    component: CNavItem,
    name: 'Role',
    to: '/role',
    icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
    isAdmin: true,
    isMasterDistributor: true,
    isDistributor: true,
    isRetailer: true,
  },
]

export default _nav
